# Generated by Django 2.2 on 2019-05-01 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.CharField(max_length=100)),
                ('gym_level', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=100)),
                ('movement_type', models.CharField(max_length=100)),
                ('compound_isolation', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=100)),
                ('major_muscles', models.CharField(max_length=100)),
                ('minor_muscles', models.CharField(max_length=100)),
                ('beginner', models.CharField(max_length=100)),
                ('intermediate', models.CharField(max_length=100)),
                ('advanced', models.CharField(max_length=100)),
                ('sl', models.CharField(max_length=100)),
                ('gvt', models.CharField(max_length=100)),
                ('main_lift', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
