# Generated by Django 2.2 on 2019-05-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_moderator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
